### ISSUE TITLE
Switch to flask

### ISSUE THREAD

**Issue by vcmikuu** [Panther-Dust22/TikTok-Live-TTS-BSR-Injector#1]
I've looked through the files and saw that the site is running completely just though an browser.. I think if you already use Python you can use a Flask server to integrate python into your site. Could be useful for some things ig

**Comment by Panther-Dust22** [comment]
The site used for the bsr injector and twitch pass through is self hosted, everything runs on the host pc, using flask would make almost no difference, I did think about it previously, and I did have the bsr injector running on python as one of my beta versions, but it made sense just to run it as a separate entity to the TTS, one for the maintenance and update side of things but 2 so the end user doesn't have to use both if they don't want to, it also means less resources on the host pc as it's not running an additional service (flask server), and when it comes to vr games it makes a big difference.

But thanks I do appreciate the feedback

**Comment by Panther-Dust22** [comment]
Also I'm kinda new to the coding scene for python and JavaScript

**Comment by vcmikuu** [comment]
That was everything! I just wanted to ask, but if you plan to enhance your tool, you should def look at selenium.
